name = "robotics-club-api"
main = "src/index.ts"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787

[vars]
FRONTEND_URL = "http://localhost:3000"
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "robotics-club-db-dev"
database_id = "local-placeholder"

# STAGING

[env.staging]
name = "robotics-club-api-staging"

[env.staging.vars]
ENVIRONMENT = "staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "robotics-club-db-staging"
database_id = "staging-placeholder"

# PRODUCTION

[env.production]
name = "robotics-club-api-production"

[env.production.vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://robotics-club-frontend-production.seku.workers.dev"

[[env.production.d1_databases]]
binding = "DB"
database_name = "robotics-club-db-production"
database_id = "195f1422-3088-43ef-9133-8a449b5e6b95"